monkeys: [
  {
    id: 0,
    startingItems: [Array],
    operation: "*",
    operand: 13,
    testDivisible: 7,
    toMonkeyIfTestTrue: 1,
    toMonkeyIfTestFalse: 5,
  },
  {
    id: 1,
    startingItems: [Array],
    operation: "*",
    operand: -1, // -1 for old * old
    testDivisible: 3,
    toMonkeyIfTestTrue: 3,
    toMonkeyIfTestFalse: 5,
  },
  {
    id: 2,
    startingItems: [Array],
    operation: "+",
    operand: 7,
    testDivisible: 2,
    toMonkeyIfTestTrue: 0,
    toMonkeyIfTestFalse: 4,
  },
  {
    id: 3,
    startingItems: [Array],
    operation: "+",
    operand: 4,
    testDivisible: 11,
    toMonkeyIfTestTrue: 7,
    toMonkeyIfTestFalse: 6,
  },
  {
    id: 4,
    startingItems: [Array],
    operation: "*",
    operand: 19,
    testDivisible: 17,
    toMonkeyIfTestTrue: 1,
    toMonkeyIfTestFalse: 0,
  },
  {
    id: 5,
    startingItems: [Array],
    operation: "+",
    operand: 3,
    testDivisible: 5,
    toMonkeyIfTestTrue: 7,
    toMonkeyIfTestFalse: 3,
  },
  {
    id: 6,
    startingItems: [Array],
    operation: "+",
    operand: 5,
    testDivisible: 13,
    toMonkeyIfTestTrue: 4,
    toMonkeyIfTestFalse: 2,
  },
  {
    id: 7,
    startingItems: [Array],
    operation: "+",
    operand: 1,
    testDivisible: 19,
    toMonkeyIfTestTrue: 2,
    toMonkeyIfTestFalse: 6,
  },
];
